spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: 'jdbc:sqlserver://localhost:1433;database=test;encrypt=true;encrypt=true;trustServerCertificate=true'
    username: 'sa'
    password: '147852Fang+'

mybatis:
  mapper-locations: classpath:/mapper/*.xml





