spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: 'jdbc:sqlserver://127.0.0.1;database=test'
    username: 'sa'
    password: 'sqlserver@TEST'

  data:
    redis:
      host: '127.0.0.1'
      port: 6739
      password: 'redis@TEST'
